name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  # https://github.com/typegoose/typegoose/blob/1637a5247a2543d3088e04579f26294dc7260043/.github/workflows/tests.yml
  # Download mongodb binaries to ~/.cache/mongodb-binaries instead of local node_modules
  # Used for separate cache
  MONGOMS_PREFER_GLOBAL_PATH: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24.13.0
        cache: "npm"

    # https://github.com/typegoose/typegoose/blob/1637a5247a2543d3088e04579f26294dc7260043/.github/workflows/tests.yml
    - name: Load MongoDB binary cache
      id: cache-mongodb-binaries
      uses: actions/cache@v5
      with:
        path: ~/.cache/mongodb-binaries
        key: ${{ runner.os }}-mongodb-binaries-${{ hashFiles('**/package-lock.json') }}

    - name: Install root dependencies
      run: npm ci
    - name: Install client dependencies
      run: npm ci --prefix ./client
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
